/**
 * Symbols class
 * - holds all symbols
 * - automatic generated by Symbol.Collator.py
 */
var Symbols = Class.extend({
	
	symbols : [],
	path : "",
	
	construct : function(path) {
		this.path = path;
	},
	
	getSymbols : function() {
		//this.symbols.push(["name", "", OpenLayers.Filter.Comparison.EQUAL_TO, this.path + "/images/symbols/cluster.png", false]);
		this.symbols.push(["cluster", "true", OpenLayers.Filter.Comparison.EQUAL_TO, this.path + "/images/symbols/cluster.png", false]);
		return this.symbols;
	},
	
	getElseSymbol : function() {
		return this.path + "/images/symbols/unknown.png";
	}
});